### ISSUE TITLE
[Guide] Deployment on Synology NAS

### ISSUE THREAD

**Issue by Mickey016** [SamR1/docker-fittrackee#32]
Hi,

  after some tinkering, I managed to run Fittrackee on my Synology (DS1019+ but should be the same for every x86 model).

Here are the steps I followed :
- connect via SSH
- create a working directory (for example /volume1/docker/fittrackee)
- download and decompress the repo
- create the .env file with your custom settings

```
# Custom variables initialisation
# All uncommented variables must be initialized

# Host directory to store FitTrackee logs (must be an absolute path)
FITTRACKEE_LOG_DIR=/logs

# Application
# directories are located in the docker container
FLASK_APP=fittrackee
FLASK_SKIP_DOTENV=1
PORT=5000
APP_SETTINGS=fittrackee.config.ProductionConfig
APP_SECRET_KEY='please change me'
APP_LOG=/logs/fittrackee.log
UPLOAD_FOLDER=/uploads  # must match docker-compose config
# gunicorn settings
# see https://docs.gunicorn.org/en/stable/settings.html#worker-processes
APP_WORKERS=2
GUNICORN_LOG=/logs/gunicorn.log
GUNICORN_TIMEOUT=300
GUNICORN_THREADS=4
# workers settings
WORKERS_PROCESSES=2

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
# fittrackee user password must match the password in database creation script (db/create.sql)
DATABASE_URL=postgresql://fittrackee:fittrackee@fittrackee-db:5432/fittrackee
#DATABASE_DISABLE_POOLING=

# Redis (required for API rate limits, email sending and user export)
#REDIS_URL=redis://redis:6379

# API rate limits (needs redis running)
#API_RATE_LIMITS="300 per 5 minutes"

# Emails
# since fittrackee 0.6.5, email sending can be disabled
# see documentation https://samr1.github.io/FitTrackee/installation.html#emails
#UI_URL=
#EMAIL_URL=
#SENDER_EMAIL=

# Workouts
#export TILE_SERVER_URL=
#export STATICMAP_SUBDOMAINS=
#export MAP_ATTRIBUTION=
#export DEFAULT_STATICMAP=False

# Weather
# available weather API providers: darksky, visualcrossing
#export WEATHER_API_PROVIDER=
#export WEATHER_API_KEY=
```

- in the same directory (/volume1/docker/fittrackee), create two folders : "uploads" and "logs"
- modify the docker-compose.yml file to ensure port 5000 is mapped at your convenience

 ```
version: '3.8'

services:

  fittrackee-db:
    container_name: fittrackee-db
    build: ./db
    env_file:
      - /volume1/docker/fittrackee/.env


  fittrackee:
    container_name: fittrackee
    build: .
    ports:
      - "15000:5000"
    env_file:
      - /volume1/docker/fittrackee/.env
    depends_on:
      - fittrackee-db
    links:
      - fittrackee-db
    volumes:
      - /volume1/docker/fittrackee/uploads:/uploads:rw
      - /volume1/docker/fittrackee/logs:/logs:rw

  redis:
    container_name: fittrackee-redis
    image: "redis:latest"
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  fittrackee_upload:

```

- because the command 'make' is not available on DSM, we have to use the complete command lines as root (use "sudo -i" if needed): 

```
# docker-compose build
# docker-compose up -d
# docker-compose exec fittrackee scripts/migrate.sh
# docker-compose exec fittrackee supervisorctl start all
```

Your Fittrackee instance should be available at http://IP-of-your-NAS:5000 (or whatever port you specified in docker-compose.yml).

Register on the homepage and then use this last command to activate the admin account :

```
docker-compose exec fittrackee scripts/set-admin.sh YOURUSERNAME
```

Hope this could help some of you and keep up the good work @SamR1 !
