### ISSUE TITLE
Fails to start after make rebuild

### ISSUE THREAD

**Issue by sgofferj** [SamR1/docker-fittrackee#9]
I was on some older 0.4 version and did a `make rebuild`. The container build went through without error but the new container fails to start. The only error message is `fittrackee exited with code 3`. Please advise.

**Comment by sgofferj** [comment]
I do have customized my setup a little bit to use a central PGDB and a bind volume for the upload data.

docker-compose.yml:
```yaml
version: '3.8'

services:
  fittrackee:
    container_name: fittrackee
    build: .
    env_file:
      - .env
    volumes:
      - /storage/docker/fittrackee/data:/uploads:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fitt-service.loadbalancer.server.port=5000"
      - "traefik.docker.network=web_services"
      - "traefik.http.routers.fittrackee.entrypoints=web"
      - "traefik.http.routers.fittrackee.rule=Host(`fittrackee.xxxxxxxx.net`)"
      - "traefik.http.routers.fittrackee.middlewares=redirect@file"
      - "traefik.http.routers.fittrackee-secure.entrypoints=websecure"
      - "traefik.http.routers.fittrackee-secure.rule=Host(`fittrackee.xxxxxxxx.net`)"
      - "traefik.http.routers.fittrackee-secure.tls=true"
      - "traefik.http.routers.fittrackee-secure.tls.domains[0].main=fittrackee.xxxxxxxx.net"
      - "traefik.http.routers.fittrackee-secure.middlewares=hsts@file"
      - "traefik.http.routers.fittrackee-secure.service=fitt-service"

networks:
  default:
    external:
      name: web_services
```

.env:
```bash
# Custom variables initialisation

# Application
export FLASK_APP=fittrackee
export HOST=0.0.0.0
export PORT=5000
export APP_SETTINGS=fittrackee.config.ProductionConfig
export APP_SECRET_KEY='xxxxxxxxxxxx'
export APP_LOG=fittrackee.log
export UPLOAD_FOLDER=/uploads

export APP_WORKERS=2
export GUNICORN_LOG=gunicorn.log
export GUNICORN_TIMEOUT=300
export GUNICORN_THREADS=4

# Database
export DATABASE_URL=postgres://fittrackee:fittrackee@xxx.xxx.xxx.xxx:5432/fittrackee
#export DATABASE_DISABLE_POOLING=

# Emails
export UI_URL=https://fittrackee.xxxxxxxx.net
export EMAIL_URL=smtp://none:none@mail:25
export SENDER_EMAIL=webmaster@xxxxxxxx.net
export REDIS_URL=redis://redis:6379
export WORKERS_PROCESSES=2

# Activities
#export TILE_SERVER_URL=
#export MAP_ATTRIBUTION=
#export WEATHER_API_KEY=
```
